CREATE DATABASE QLKC;
USE QLKC;

CREATE TABLE PRODUCTS 
(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME_PRODUCTS VARCHAR(255) NOT NULL,
    PRICE decimal(10, 2) NOT NULL,
    DESCRIPTION_PRODUCTS TEXT,
    IMAGE VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);