# Generated by Django 5.1.4 on 2025-01-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanpham', models.CharField(max_length=255)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soluong', models.IntegerField()),
                ('tongtien', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
    