# Generated by Django 5.1.6 on 2025-02-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
